[2017-01-12 17:53:38,560][app.LiveChecker][ERROR] 无法连接http://www.panda.tv/10029
Traceback (most recent call last):
  File "/home/jack/pythoncoding/easySee/app/LiveChecker.py", line 39, in xiongmao
    r = self.s.get(url, proxies=random.choice(PROXIES)).text
  File "/home/jack/easyenv/local/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/home/jack/easyenv/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jack/easyenv/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/jack/easyenv/local/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
